name: .NET CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: Release
      TEST_PROJECT_PATH: SubsequenceFinder.Tests/SubsequenceFinder.Tests.csproj

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore SubsequenceFinder.slnx

      - name: Build
        run: dotnet build SubsequenceFinder.slnx --no-restore --configuration ${{ env.BUILD_CONFIG }}

      - name: Execute Unit Tests and Collect Coverage
        run:
          dotnet test SubsequenceFinder.Tests/SubsequenceFinder.Tests.csproj \
          --configuration ${{ env.BUILD_CONFIG }} \
          --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=cobertura \
          /p:CoverletOutput=${{ github.workspace }}/coverage/

      - name: Display Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ github.workspace }}/coverage/cobertura.xml
          format: "markdown"
